preset: symfony

enabled:
    - strict_param
    - ordered_use
    - short_array_syntax
    - phpdoc_order
    
disabled:
    - psr0
    - strict
    
finder:
    in:
        - 'src/'
        - 'tests/'
    exclude:
        - 'bin'
        - 'doc'
